# Generated by Django 5.1.6 on 2025-02-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='test_database_teacher',
        ),
    ]
